# npm login --registry="http://10.122.110.189:8081/repository/tdp-npm-group/"
#"@smartplatform:registry" "http://10.122.110.189:8081/repository/tdp-npm-group/"
#npmScopes:
#  "@smartplatform/ui-components":
#  npmAlwaysAuth: true
#  npmRegistryServer: "http://10.122.110.189:8081/repository/tdp-npm-group/"
#"registry" "http://10.122.110.189:8081/repository/tdp-npm-group/"
npmScopes:
  "@smartplatform":
    npmRegistryServer: "http://10.122.110.189:8081/repository/tdp-npm-group/"
    npmPublishRegistry: "http://10.122.110.189:8081/repository/tdp-npm-group/"
    npmAlwaysAuth: true
    npmAuthIdent: "tdp:tdp@lenovo.nexus666"
registry: "http://10.122.110.189:8081/repository/tdp-npm-group/"
